#! /usr/bin/env python
import pymongo
#from pymongo import MongoClient
import csv

myclient=pymongo.MongoClient("mongodb://pluton.i3a.uclm.es:27017/")
mydb=myclient["kikeDev"]
mycol=mydb["AirMeasurement"]

x=[]
consulta =list(mycol.find().sort("_id",-1).limit(3))



for i in consulta:
         x.append(i)

myFile=open('datos.csv','w')
with myFile:
        writer=csv.writer(myFile)


        writer.writerow(x)







--------------------EXPORTAR TODO EL FICHERO DE DATOS A UN FICHERO .CSV----------------------
mongoexport --uri='mongodb://localhost:27017/prueba' --collection=prueba --out=fichero.csv


